# Name of the Customer / Website
customer: demo-school

# Customer type (Options are school-india, school-international, college-india, college-international, institute-india, institute-international, corporate-india, corporate-international)
customer-type: college-india

# HOME Page of the website. Default Value: https://<customer-name>.doorward.tech.
app_domain: demo-school.doorward.tech

# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
welcomepage_domain: www.doorward.tech

# Application URL. Default Value: https://<customer-name>.doorward.tech
app_url: https://demo-school.doorward.tech

# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.tech
samvadam_domain: samvadam.demo-school.doorward.tech

# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.tech
thala_domain: thala.demo-school.doorward.tech

# Public Domain for openvidu API.
openviduapi_url: https://vidu.demo-school.doorward.tech/api/

# Public Domain for OpenVidu API
openviduapi_domain: vidu.demo-school.doorward.tech

# Public URL of Openvidu Server
classrooms_url: classrooms.develop.doorward.tech

# Name of the Website. Default Value: <Customer-Name>
websitename: demo-school

# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: demo-school-doorward

# Secret to use to pull docker images for deployment
imagePullSecrets:
  - name: deploy-pull-harbor

# Override default variables for stage environments

image:
  swagat:
    repository: core.harbor.doorward.tech/doorward/swagat@sha256
    version: 0b4bbb622ec1ee3ce36e8b4d7afe41d8a570602730951fd024cab33452a331d9
    pullPolicy: Always
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: core.harbor.doorward.tech/doorward/thala@sha256
    version: c2b9f98a0c35ce3a01304f1cb61422e235ecfcd27bdb409a015622557a2afe13
    pullPolicy: Always
  samvadam:
    repository: core.harbor.doorward.tech/doorward/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: core.harbor.doorward.tech/doorward/chuchu@sha256
    version: 0127539bd5fc7c1bce74e1659b6fa951714b6918ccf31c0d9fba21933592982a
    pullPolicy: Always
  vidu:
    repository: core.harbor.doorward.tech/doorward/vidu@sha256
    version: 75f8b409ee884eba2334c87a0e143181fb5046575fec4d831b95f0c0e3eb0040
    pullPolicy: Always


organization:
  # Organization Logo
    logo: "https://doorward.s3.amazonaws.com/logos/download1.png"

  # Display Name of Organization
    name: Doorward E-Learning

  # Application URL
    website: demo-school.doorward.tech

  #Organization Admin Email ID
    email: info@doorward.tech
