apiVersion: v1
kind: Service
metadata:
  name: {{ include "vidu.fullname" . }}
  labels:
    {{- include "vidu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.openviduapi_containerport }}
      protocol: TCP
      name: http
  selector:
    {{- include "vidu.selectorLabels" . | nindent 4 }}
