apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thala.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-doorward
  labels:
    {{- include "thala.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "thala.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thala.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.thala.repository }}:{{ .Values.image.thala.version }}"
          imagePullPolicy: {{ .Values.image.thala.pullPolicy }}
          ports:
            - name: {{ .Values.service.protocol }}
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 100
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: {{ .Values.service.targetport }}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: {{ .Values.container.startupseconds }}
            successThreshold: 1
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .Values.service.targetport }}
          env:
          - name: OPENVIDU_API_PORT
            valueFrom:
              configMapKeyRef:
                key: OPENVIDU_API_PORT
                name: {{ .Values.customer -}}-config
          - name: OPENVIDU_API_URL
            valueFrom:
              configMapKeyRef:
                key: OPENVIDU_API_URL
                name: {{ .Values.customer -}}-config
          - name: OPENVIDU_URL
            valueFrom:
              configMapKeyRef:
                key: OPENVIDU_URL
                name: {{ .Values.customer -}}-config
          - name: OPENVIDU_USERNAME
            valueFrom:
              configMapKeyRef:
                key: OPENVIDU_USERNAME
                name: {{ .Values.customer -}}-config
          - name: OPENVIDU_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: OPENVIDU_PASSWORD
                name: {{ .Values.customer -}}-config
          - name: DOORWARD_ADMIN_EMAIL
            valueFrom:
              configMapKeyRef:
                key: DOORWARD_ADMIN_EMAIL
                name: {{ .Values.customer -}}-config
          - name: ORGANIZATION
            value: {{ .Values.customer }}
          - name: USE_LATENCY
            valueFrom:
              configMapKeyRef:
                key: USE_LATENCY
                name: {{ .Values.customer -}}-config
          - name: DOORWARD_DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                key: DATABASE_USERNAME
                name: {{ .Values.customer -}}-config
          - name: DOORWARD_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                key: DATABASE_HOST
                name: {{ .Values.customer -}}-config
          - name: DOORWARD_DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                key: DATABASE_PORT
                name: {{ .Values.customer -}}-config
          - name: DOORWARD_DATABASE
            valueFrom:
              configMapKeyRef:
                key: DATABASE_NAME
                name: {{ .Values.customer -}}-config
          - name: DOORWARD_DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: DATABASE_PASSWORD
                name: {{ .Values.customer -}}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
