version: '2.1'

volumes:
  doorward_data:
    external: true

services:
  doorward:
    image: dev_doorward:latest
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
  doorward_frontend:
    image: dev_doorward:latest
    container_name: doorward_frontend
    links:
      - doorward_rest_api
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    env_file:
      - ../../.env
    environment:
      REACT_APP_BASE_URL: http://localhost:7000/api/v1/
      REACT_APP_REQUEST_DELAY: 500
      DOORWARD_WEBSITE_LINK: http://localhost:3006
    ports:
      - '3005:3000'
    expose:
      - '3000'
    entrypoint:
      - /usr/app/apps/doorward-frontend/entrypoint.sh
    depends_on:
      doorward_rest_api:
        condition: service_started
      doorward_website:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:3000']
      interval: 10s
      timeout: 10s
      retries: 20
  doorward_rest_api:
    image: dev_doorward:latest
    container_name: doorward_node_backend
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@doorward_node_database:5432/doorward
      FRONTEND_URL: http://localhost:3005
    ports:
      - '7000:7000'
    expose:
      - '7000'
    entrypoint:
      - /usr/app/apps/doorward-node-backend/entrypoint.sh
    depends_on:
      doorward_node_database:
        condition: service_healthy
      doorward_openvidu:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:7000']
      interval: 10s
      timeout: 10s
      retries: 20
  openvidu_api:
    image: dev_doorward:latest
    container_name: openvidu_backend
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    ports:
      - '3333:3333'
    expose:
      - '3333'
    entrypoint:
      - /usr/app/apps/openvidu-backend/entrypoint.sh
    depends_on:
      doorward_openvidu:
        condition: service_started
  doorward_website:
    image: dev_doorward:latest
    container_name: doorward_website
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    environment:
      DOORWARD_APPLICATION_LINK: http://localhost:3005
    ports:
      - '3006:3001'
    expose:
      - '3001'
    entrypoint:
      - /usr/app/apps/doorward-website/entrypoint.sh
    depends_on:
      doorward_rest_api:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:3001']
      interval: 10s
      timeout: 10s
      retries: 20
  doorward_node_database:
    image: postgres:9.6-alpine
    container_name: doorward_node_backend_db
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doorward
    volumes:
      - doorward_data:/var/lib/postgresql/doorward
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 10
  doorward_openvidu:
    image: doorward_openvidu:latest
    build:
      context: ./openvidu
      dockerfile: Dockerfile
    container_name: doorward_openvidu
    env_file:
      - openvidu/.env
    ports:
      - '443:4443'
    environment:
      OPENVIDU_SECRET: password
      OPENVIDU_WEBHOOK: 'true'
