version: '2.1'

volumes:
  edudoor_data:
    external: true

services:
  edudoor_frontend:
    container_name: edudoor_frontend
    build:
      context: ../../edudoor_frontend
      dockerfile: docker/dev/Dockerfile
    links:
      - edudoor_backend
    volumes:
      - /usr/app/node_modules
      - ../../edudoor_frontend:/usr/app
    env_file:
      - ../../edudoor_frontend/.env
    environment:
      REACT_APP_BASE_URL: http://localhost:5000/openolat/restapi/
      REACT_APP_REQUEST_DELAY: 0
    ports:
      - '3005:3000'
    expose:
      - '3000'
    command:
      - yarn
      - start
    depends_on:
      edudoor_backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:3000']
      interval: 10s
      timeout: 10s
      retries: 20
  edudoor_backend:
    image: gitaumoses4/openolat-edudoor
    container_name: edudoor_backend
    links:
      - edudoor_database
    ports:
      - '5000:8080'
    depends_on:
      edudoor_database:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:8080']
      interval: 10s
      timeout: 10s
      retries: 20
  edudoor_database:
    image: gitaumoses4/edudoor_database
    container_name: edudoor_backend_db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openolat
    volumes:
      - edudoor_data:/var/lib/postgresql/edudoor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
