apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-doorward
  labels:
    {{- include "chat.labels" . | nindent 4 }}
    customer: {{ .Values.customer }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "chat.selectorLabels" . | nindent 4 }}
