# Name of the Customer / Website
customer: scoresnranks

# HOME Page of the website. Default Value: https://<customer-name>.doorward.tech.
app_domain: lms.scoresnranks.in

# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
# welcomepage_domain: www.doorward.tech

# Application URL. Default Value: https://<customer-name>.doorward.tech
app_url: https://lms.scoresnranks.in

# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.tech
samvadam_domain: samvadam.scoresnranks.doorward.tech

# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.tech
thala_domain: thala.scoresnranks.doorward.tech

# Name of the Website. Default Value: <Customer-Name>
websitename: scoresnranks

# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: scoresnranks-doorward

# Override default variables for stage environments

image:
  swagat:
    repository: core.harbor.doorward.tech/doorward/swagat
    version: 1.1.0
    pullPolicy: IfNotPresent
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: core.harbor.doorward.tech/doorward/thala@sha256
    version: e4bdda21c51f6f33834bf2e59f473500b84c9297f163674046b978ef6673f736
    pullPolicy: IfNotPresent
  samvadam:
    repository: core.harbor.doorward.tech/doorward/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: core.harbor.doorward.tech/doorward/chuchu@sha256
    version: 1123770e852738f249267edc3f19d79aca2e9e586703307ceee46531809322b9
    pullPolicy: IfNotPresent

organization:
  # Organization Logo
  logo: "https://doorwardlms.s3.amazonaws.com/scoresnranks/scoresnranks.jpg"
  # Display Name of Organization
  name: Scores N ranks
  # Application URL
  website: lms.scoresnranks.in
  #Organization Admin Email ID
  email: Kandasamy@pppindia.com
