#apiVersion: cert-manager.io/v1alpha3
#kind: Issuer
#metadata:
#  creationTimestamp: "2020-06-12T14:11:06Z"
#  generation: 1
#  name: letsencrypt-prod
#  namespace: default
#spec:
#  acme:
#    email: basil@doorward.tech
#    privateKeySecretRef:
#      name: letsencrypt-prod
#    server: https://acme-v02.api.letsencrypt.org/directory
#    solvers:
#    - http01:
#        ingress:
#          class: nginx
