import {MigrationInterface, QueryRunner} from "typeorm";

export class AddPublicExamLinkToAssessmentOptions1634025078799 implements MigrationInterface {
    name = 'AddPublicExamLinkToAssessmentOptions1634025078799'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Meetings" DROP CONSTRAINT "FK_6936e05362d215e35f6bd0a3525"`);
        await queryRunner.query(`ALTER TABLE "MeetingRooms" DROP CONSTRAINT "FK_6276060dcbb950fa2192887b24d"`);
        await queryRunner.query(`ALTER TABLE "MeetingRoomMembers" DROP CONSTRAINT "FK_5237b8d8d684872f971703b2be1"`);
        await queryRunner.query(`ALTER TABLE "Groups" DROP CONSTRAINT "FK_a90075be409849b37aee9c9610f"`);
        await queryRunner.query(`ALTER TABLE "GroupMembers" DROP CONSTRAINT "FK_824999b5a7a3cd3b573c7d4dd7f"`);
        await queryRunner.query(`ALTER TABLE "PasswordResets" DROP CONSTRAINT "FK_8066dfbf52a62fb59ba0fddf38a"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "FK_1612823a86e1cc991e52bd8b664"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "FK_856956eb7e126c05fe0c9082051"`);
        await queryRunner.query(`ALTER TABLE "StudentCourses" DROP CONSTRAINT "FK_e2f1b1433c40de94a71153c333d"`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroupComments" DROP CONSTRAINT "FK_284fe25783622bcc480d86eca4e"`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroupComments" DROP CONSTRAINT "FK_f8b7fdf175b5da5b4a28593f99b"`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroups" DROP CONSTRAINT "FK_60202a59ece6c1a43758e018c7e"`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroups" DROP CONSTRAINT "FK_29d2bd8f4495b41649d63934db6"`);
        await queryRunner.query(`ALTER TABLE "Courses" DROP CONSTRAINT "FK_c47efca7e56913a7495071596c7"`);
        await queryRunner.query(`ALTER TABLE "Modules" DROP CONSTRAINT "FK_b4f3f0fee39ddc2b64b6109ee74"`);
        await queryRunner.query(`ALTER TABLE "Files" DROP CONSTRAINT "FK_1221481278810083fabc00998a2"`);
        await queryRunner.query(`ALTER TABLE "ModuleItems" DROP CONSTRAINT "FK_31e6c5890c29399bf792c85b94f"`);
        await queryRunner.query(`ALTER TABLE "ModuleItems" DROP CONSTRAINT "FK_591df46e6be606df67c9dd1cec9"`);
        await queryRunner.query(`ALTER TABLE "QuestionSections" DROP CONSTRAINT "FK_13ae843d4be7f19d73bd879ee39"`);
        await queryRunner.query(`ALTER TABLE "Questions" DROP CONSTRAINT "FK_3594b03bb41a3dfa3b5601ce0ad"`);
        await queryRunner.query(`ALTER TABLE "Answers" DROP CONSTRAINT "FK_bd66877bf345afa88c7ac760f25"`);
        await queryRunner.query(`ALTER TABLE "AssignmentSubmissions" DROP CONSTRAINT "FK_65674b3b65b4ac62cd73e4a8ee1"`);
        await queryRunner.query(`ALTER TABLE "CourseManagers" DROP CONSTRAINT "FK_589aca480c62c360a11ce713d97"`);
        await queryRunner.query(`ALTER TABLE "AssessmentSubmission" DROP CONSTRAINT "FK_10c34cc42407f48a424f969ba3e"`);
        await queryRunner.query(`ALTER TABLE "AssessmentSubmission" DROP CONSTRAINT "FK_7bf45a696fee8696ddaaa5c98a6"`);
        await queryRunner.query(`CREATE TABLE "ChatMessageActivityEntity" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "readAt" TIMESTAMP, "messageId" character varying, "userId" character varying, CONSTRAINT "PK_f0bb1b22b0b6a8d6d8ecc062fa9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "ChatMessages_status_enum" AS ENUM('0', '1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "ChatMessages" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "text" character varying NOT NULL, "status" "ChatMessages_status_enum" NOT NULL DEFAULT '0', "numRecipients" integer NOT NULL DEFAULT 0, "numDelivered" integer NOT NULL DEFAULT 0, "numRead" integer NOT NULL DEFAULT 0, "conversationId" character varying, "senderId" character varying, CONSTRAINT "PK_55cbfe04f86a557414495c8b273" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Conversations" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "title" character varying NOT NULL, "avatar" character varying NOT NULL, "directMessage" boolean NOT NULL DEFAULT true, "groupId" character varying, CONSTRAINT "REL_049a6f210c3bdaab956caa89ae" UNIQUE ("groupId"), CONSTRAINT "PK_44f6c6ade92598cd70087acf2a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Configurations" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "key" text NOT NULL, "value" text, CONSTRAINT "UQ_f3ce91b0635d798c6ecd17dfa50" UNIQUE ("key"), CONSTRAINT "PK_07f0562e3292e084a7e835c4405" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "Meetings" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "MeetingRooms" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "MeetingRoomMembers" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "Groups" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "GroupMembers" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "PasswordResets" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "StudentCourses" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroupComments" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroups" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "Courses" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "Modules" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "Files" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "ModuleItems" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "QuestionSections" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "Questions" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "Answers" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "AssignmentSubmissions" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "CourseManagers" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "AssessmentSubmission" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "Roles" DROP COLUMN "name"`);
        await queryRunner.query(`DROP TYPE "public"."Roles_name_enum"`);
        await queryRunner.query(`ALTER TABLE "Roles" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Roles" ADD CONSTRAINT "UQ_8eadedb8470c92966389ecc2165" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "UQ_ffc81a3b97dcbf8e320d5106c0d" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "QuestionSections" ALTER COLUMN "config" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ChatMessageActivityEntity" ADD CONSTRAINT "FK_f6614f8c503a20b14ce861bbdeb" FOREIGN KEY ("messageId") REFERENCES "ChatMessages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChatMessageActivityEntity" ADD CONSTRAINT "FK_6c16ab7caf112276e800c2469db" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChatMessages" ADD CONSTRAINT "FK_7a27218c621e959b6ba6d64ed2e" FOREIGN KEY ("conversationId") REFERENCES "Conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChatMessages" ADD CONSTRAINT "FK_4a68f02e80dd448a69ee7458b09" FOREIGN KEY ("senderId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Conversations" ADD CONSTRAINT "FK_049a6f210c3bdaab956caa89ae5" FOREIGN KEY ("groupId") REFERENCES "Groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "FK_856956eb7e126c05fe0c9082051" FOREIGN KEY ("createdById") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroupComments" ADD CONSTRAINT "FK_f8b7fdf175b5da5b4a28593f99b" FOREIGN KEY ("authorId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroups" ADD CONSTRAINT "FK_29d2bd8f4495b41649d63934db6" FOREIGN KEY ("creatorId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ModuleItems" ADD CONSTRAINT "FK_591df46e6be606df67c9dd1cec9" FOREIGN KEY ("createdBy") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AssessmentSubmission" ADD CONSTRAINT "FK_7bf45a696fee8696ddaaa5c98a6" FOREIGN KEY ("assessmentId") REFERENCES "ModuleItems"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "AssessmentSubmission" DROP CONSTRAINT "FK_7bf45a696fee8696ddaaa5c98a6"`);
        await queryRunner.query(`ALTER TABLE "ModuleItems" DROP CONSTRAINT "FK_591df46e6be606df67c9dd1cec9"`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroups" DROP CONSTRAINT "FK_29d2bd8f4495b41649d63934db6"`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroupComments" DROP CONSTRAINT "FK_f8b7fdf175b5da5b4a28593f99b"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "FK_856956eb7e126c05fe0c9082051"`);
        await queryRunner.query(`ALTER TABLE "Conversations" DROP CONSTRAINT "FK_049a6f210c3bdaab956caa89ae5"`);
        await queryRunner.query(`ALTER TABLE "ChatMessages" DROP CONSTRAINT "FK_4a68f02e80dd448a69ee7458b09"`);
        await queryRunner.query(`ALTER TABLE "ChatMessages" DROP CONSTRAINT "FK_7a27218c621e959b6ba6d64ed2e"`);
        await queryRunner.query(`ALTER TABLE "ChatMessageActivityEntity" DROP CONSTRAINT "FK_6c16ab7caf112276e800c2469db"`);
        await queryRunner.query(`ALTER TABLE "ChatMessageActivityEntity" DROP CONSTRAINT "FK_f6614f8c503a20b14ce861bbdeb"`);
        await queryRunner.query(`ALTER TABLE "QuestionSections" ALTER COLUMN "config" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "UQ_ffc81a3b97dcbf8e320d5106c0d"`);
        await queryRunner.query(`ALTER TABLE "Roles" DROP CONSTRAINT "UQ_8eadedb8470c92966389ecc2165"`);
        await queryRunner.query(`ALTER TABLE "Roles" DROP COLUMN "name"`);
        await queryRunner.query(`CREATE TYPE "public"."Roles_name_enum" AS ENUM('SUPER_ADMINISTRATOR', 'TEACHER', 'STUDENT')`);
        await queryRunner.query(`ALTER TABLE "Roles" ADD "name" "Roles_name_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "AssessmentSubmission" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CourseManagers" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "AssignmentSubmissions" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Answers" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Questions" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "QuestionSections" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ModuleItems" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Files" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Modules" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Courses" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroups" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroupComments" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "StudentCourses" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Users" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "PasswordResets" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "GroupMembers" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Groups" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "MeetingRoomMembers" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "MeetingRooms" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Meetings" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "Configurations"`);
        await queryRunner.query(`DROP TABLE "Conversations"`);
        await queryRunner.query(`DROP TABLE "ChatMessages"`);
        await queryRunner.query(`DROP TYPE "ChatMessages_status_enum"`);
        await queryRunner.query(`DROP TABLE "ChatMessageActivityEntity"`);
        await queryRunner.query(`ALTER TABLE "AssessmentSubmission" ADD CONSTRAINT "FK_7bf45a696fee8696ddaaa5c98a6" FOREIGN KEY ("assessmentId") REFERENCES "ModuleItems"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AssessmentSubmission" ADD CONSTRAINT "FK_10c34cc42407f48a424f969ba3e" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CourseManagers" ADD CONSTRAINT "FK_589aca480c62c360a11ce713d97" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AssignmentSubmissions" ADD CONSTRAINT "FK_65674b3b65b4ac62cd73e4a8ee1" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Answers" ADD CONSTRAINT "FK_bd66877bf345afa88c7ac760f25" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Questions" ADD CONSTRAINT "FK_3594b03bb41a3dfa3b5601ce0ad" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "QuestionSections" ADD CONSTRAINT "FK_13ae843d4be7f19d73bd879ee39" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ModuleItems" ADD CONSTRAINT "FK_591df46e6be606df67c9dd1cec9" FOREIGN KEY ("createdBy") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ModuleItems" ADD CONSTRAINT "FK_31e6c5890c29399bf792c85b94f" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Files" ADD CONSTRAINT "FK_1221481278810083fabc00998a2" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Modules" ADD CONSTRAINT "FK_b4f3f0fee39ddc2b64b6109ee74" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Courses" ADD CONSTRAINT "FK_c47efca7e56913a7495071596c7" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroups" ADD CONSTRAINT "FK_29d2bd8f4495b41649d63934db6" FOREIGN KEY ("creatorId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroups" ADD CONSTRAINT "FK_60202a59ece6c1a43758e018c7e" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroupComments" ADD CONSTRAINT "FK_f8b7fdf175b5da5b4a28593f99b" FOREIGN KEY ("authorId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DiscussionGroupComments" ADD CONSTRAINT "FK_284fe25783622bcc480d86eca4e" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StudentCourses" ADD CONSTRAINT "FK_e2f1b1433c40de94a71153c333d" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "FK_856956eb7e126c05fe0c9082051" FOREIGN KEY ("createdById") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "FK_1612823a86e1cc991e52bd8b664" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PasswordResets" ADD CONSTRAINT "FK_8066dfbf52a62fb59ba0fddf38a" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GroupMembers" ADD CONSTRAINT "FK_824999b5a7a3cd3b573c7d4dd7f" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Groups" ADD CONSTRAINT "FK_a90075be409849b37aee9c9610f" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "MeetingRoomMembers" ADD CONSTRAINT "FK_5237b8d8d684872f971703b2be1" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "MeetingRooms" ADD CONSTRAINT "FK_6276060dcbb950fa2192887b24d" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Meetings" ADD CONSTRAINT "FK_6936e05362d215e35f6bd0a3525" FOREIGN KEY ("organizationId") REFERENCES "Organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
