export const FETCH_STUDENT_REPORT_LIST = 'FETCH_STUDENT_REPORT_LIST';
export const FETCH_STUDENT_REPORT = 'FETCH_STUDENT_REPORT';
export const FETCH_COURSE_CREATOR_REPORT_LIST = 'FETCH_COURSE_CREATOR_REPORT_LIST';
