apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  docker-php-ext-uploads.ini: |
    post_max_size = 250M
    upload_max_filesize = 250M
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:5.6-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        - name: php-config
          mountPath: /usr/local/etc/php/conf.d/uploads.ini
          subPath: uploads.ini
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
      - name: php-config
        configMap:
          name: php-config
          items:
            - key: "docker-php-ext-uploads.ini"
              path: "uploads.ini"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.org/client-max-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  name: wordpress-ingress

spec:
  rules:
    - host: www.edudoor.org
      http:
        paths:
          - backend:
              serviceName: wordpress
              servicePort: 80
            path: /
    - host: edudoor.org
      http:
        paths:
          - backend:
              serviceName: wordpress
              servicePort: 80
            path: /
    - host: doorward.tech
      http:
        paths:
          - backend:
              serviceName: wordpress
              servicePort: 80
            path: /
    - host: www.doorward.tech
      http:
        paths:
          - backend:
              serviceName: wordpress
              servicePort: 80
            path: /
    - host: doorward.org
      http:
        paths:
          - backend:
              serviceName: wordpress
              servicePort: 80
            path: /
    - host: www.doorward.org
      http:
        paths:
          - backend:
              serviceName: wordpress
              servicePort: 80
            path: /
  tls:
  - hosts:
    - doorward.tech
    - doorward.tech
    - www.doorward.tech
    - doorward.org
    - www.doorward.org
    - edudoor.org
    - www.edudoor.org
    secretName: www.doorward.tech
