# Name of the Customer / Website
customer: basil

# HOME Page of the website. Default Value: https://<customer-name>.doorward.tech.
app_domain: basil.doorward.tech

# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
welcomepage_domain: beta.doorward.tech

# Application URL. Default Value: https://<customer-name>.doorward.tech
app_url: https://basil.doorward.tech

# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.tech
samvadam_domain: samvadam.basil.doorward.tech

# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.tech
thala_domain: thala.basil.doorward.tech

# Name of the Website. Default Value: <Customer-Name>
websitename: basil

# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: basil-doorward

# Override default variables for stage environments

image:
  swagat:
    repository: core.harbor.doorward.tech/doorward/swagat
    version: 1.1.0
    pullPolicy: Always
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: core.harbor.doorward.tech/doorward/thala
    version: 1.1.0
    pullPolicy: Always
  samvadam:
    repository: core.harbor.doorward.tech/doorward/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: core.harbor.doorward.tech/doorward/chuchu
    version: 1.1.0
    pullPolicy: Always

organization:
  # Organization Logo
  logo: "https://doorward.s3.amazonaws.com/logos/download1.png"
  # Display Name of Organization
  name: DevOps-Training
  # Application URL
  website: basil.doorward.tech
  #Organization Admin Email ID
  email: info@doorward.tech
