releases:
  - name: luims-thaladb
    namespace: luims-doorward
    labels:
      stage: 1
      name: thaladb
    chart: ../../charts/apps/thaladb
    values:
      - config.yaml

  - name: luims-samvadam
    namespace: luims-doorward
    labels:
      stage: 2
      name: samvadam
    chart: ../../charts/apps/samvadam
    needs:
      - luims-doorward/luims-thaladb
    values:
      - config.yaml

  - name: luims-thala
    namespace: luims-doorward
    labels:
      stage: 2
      name: thala
    chart: ../../charts/apps/thala
    needs:
      - luims-doorward/luims-thaladb
    values:
      - config.yaml

  - name: luims-chuchu
    namespace: luims-doorward
    labels:
      stage: 2
      name: chuchu
    chart: ../../charts/apps/chuchu
    needs:
      - luims-doorward/luims-thaladb
    values:
      - config.yaml
