releases:
  - name: psaowa-makonis-config
    namespace: psaowa-makonis-doorward
    labels:
      stage: 0
      name: config
    chart: ../../charts/apps/config
    values:
      - config.yaml

  - name: psaowa-makonis-thaladb
    namespace: psaowa-makonis-doorward
    labels:
      stage: 1
      name: thaladb
    chart: ../../charts/apps/thaladb
    values:
      - config.yaml

  - name: psaowa-makonis-samvadam
    namespace: psaowa-makonis-doorward
    labels:
      stage: 2
      name: samvadam
    chart: ../../charts/apps/samvadam
    needs:
      - psaowa-makonis-doorward/psaowa-makonis-thaladb
    values:
      - config.yaml

  - name: psaowa-makonis-thala
    namespace: psaowa-makonis-doorward
    labels:
      stage: 2
      name: thala
    chart: ../../charts/apps/thala
    needs:
      - psaowa-makonis-doorward/psaowa-makonis-thaladb
    values:
      - config.yaml

  - name: psaowa-makonis-chuchu
    namespace: psaowa-makonis-doorward
    labels:
      stage: 2
      name: chuchu
    chart: ../../charts/apps/chuchu
    needs:
      - psaowa-makonis-doorward/psaowa-makonis-thaladb
    values:
      - config.yaml

  - name: psaowa-makonis-vidu
    namespace: psaowa-makonis-doorward
    labels:
      stage: 2
      name: vidu
    chart: ../../charts/apps/vidu
    needs:
      - psaowa-makonis-doorward/psaowa-makonis-thaladb
    values:
      - config.yaml
