# Name of the Customer / Website
customer: cttfkerala

# HOME Page of the website. Default Value: https://<customer-name>.doorward.tech.
app_domain: myaccount.cttfkerala.in

# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
welcomepage_domain: beta.doorward.tech

# Application URL. Default Value: https://<customer-name>.doorward.tech
app_url: https://myaccount.cttfkerala.in

# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.tech
samvadam_domain: samvadam.cttfkerala.doorward.tech

# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.tech
thala_domain: thala.cttfkerala.doorward.tech

# Name of the Website. Default Value: <Customer-Name>
websitename: cttfkerala

# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: cttfkerala-doorward

# Override default variables for stage environments

image:
  swagat:
    repository: core.harbor.doorward.tech/doorward/swagat
    version: 1.1.0
    pullPolicy: Always
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: core.harbor.doorward.tech/doorward/thala
    version: 1.1.0
    pullPolicy: Always
  samvadam:
    repository: core.harbor.doorward.tech/doorward/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: core.harbor.doorward.tech/doorward/chuchu
    version: 1.1.0
    pullPolicy: Always

organization:
  # Organization Logo
  logo: "https://cttfkerala.s3.amazonaws.com/cttfkerala.jpg"
  # Display Name of Organization
  name: "CTTF Kerala"
  # Application URL
  website: cttfkerala.doorward.tech
  #Organization Admin Email ID
  email: archanaraj10@gmail.com
