export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST';
export const ADD_STUDENT = 'ADD_STUDENT';
export const GET_STUDENT = 'GET_STUDENT';
export const CHANGE_STUDENTS_PASSWORD = 'CHANGE_STUDENTS_PASSWORD';
