# Name of the Customer / Website
customer: develop
# Customer type (Options are school-india, school-international, college-india, college-international, institute-india, institute-international, corporate-india, corporate-international)
customer-type: college-india
# HOME Page of the website. Default Value: https://<customer-name>.doorward.tech.
app_domain: develop.doorward.org
# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
welcomepage_domain: beta.doorward.org
# Application URL. Default Value: https://<customer-name>.doorward.tech
app_url: https://develop.doorward.org
# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.tech
samvadam_domain: samvadam.develop.doorward.tech
# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.tech
thala_domain: thala.develop.doorward.org
# Public Domain of meet ui
meet_domain: meet.develop.doorward.org
# Public Chat Domain
chat_domain: chat.develop.doorward.org
# Public Domain for jitsi host
meet_host: alpha.jitsi.net
# Public Domain for openvidu API.
openviduapi_url: https://vidu.develop.doorward.tech/api/
# Public Domain for OpenVidu API
openviduapi_domain: vidu.develop.doorward.tech
# Public URL of Openvidu Server
classrooms_url: classrooms.edudoor.org
# Name of the Website. Default Value: <Customer-Name>
websitename: develop
# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: develop-doorward
chatdbpassword: 6EpnyaJkHS
postgres_password: 6EpnyaJkHS
# Secret to use to pull docker images for deployment
imagePullSecrets:
  - name: deploy-pull-mumbai
# Resources
resources:
  requests:
    cpu: 100m
    memory: 100Mi
# How many replicas
replicaCount: 2
# Override default variables for stage environments
timezone: "Asia/Kolkata"
image:
  swagat:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward-elearning/swagat@sha256
    version: 5604819335bc2939f48e16dc7c2f580c5b7f12310d36ffdd9e328110fa8ef301
    pullPolicy: Always
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward-elearning/thala@sha256
    version: 85ac8ad59a3dc01b36e943cda96305546d93b9f64753bb7ef57fb280b6382fcd
    pullPolicy: Always
  samvadam:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward-elearning/chuchu@sha256
    version: d6a6157deb7f2aa30b9fd58a33763b228dfb5765fb094108edb7d8cb5344b77b
    pullPolicy: Always
  vidu:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/vidu
    version: 1.1.2-beta
    pullPolicy: Always
  meet:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/meet
    version: 1.0.0
    pullPolicy: Always
  chat:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward-elearning/chat@sha256
    version: ac0c9b7a09291a014736bd4c236da7792e652715bf2eab30b3baa429e6d70b6e
    pullPolicy: Always
organization:
  # Organization Logo
  logo: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862570/Doorward/logo/Doorward_Logo_Small.png"
  # Display Name of Organization
  name: "Doorward E-Learning"
  # Application URL
  website: develop.doorward.tech
  #Organization Admin Email ID
  email: info@doorward.tech
# Organization Settings
DEFAULT_ORGANIZATION_NAME: develop
DEFAULT_ORGANIZATION_DISPLAY_NAME: "Doorward E-Learning"
ORGANIZATION_INGRESS_URL: "https://argoevents.doorward.tech/organization-ingress"
organization:
  name: "doorward"
  displayName: "Doorward E-Learning"
  hosts: develop.doorward.org
  lang: en
  descriptiveLogo: false
  email: info@doorward.tech
  logos:
    light: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862570/Doorward/logo/Doorward_Logo_Small.png"
    dark: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862550/Doorward/logo/Doorward_Logo_Small_Dark.png"
  description: ''
  meetingPlatform: Jitsi
  users:
    - firstName: system
      lastName: admin
      email: gitaumoses4@gmail.com
      username: administrator
      password: password
      zipCode: ''
      country: India
      city: Anantapur
      status: Active
      role: SUPER_ADMINISTRATOR
      rootOrganizationOnly: true
    - firstName: system
      lastName: admin
      email: gitaumoses4@gmail.com
      username: administrator
      password: password
      zipCode: ''
      country: India
      city: Anantapur
      status: Active
      role: ADMINISTRATOR
  roles:
    SUPER_ADMINISTRATOR:
      displayName: Super Administrator
      description: Has full access to the system
      rootOrganizationOnly: true
      privileges:
        - "*"
      exclude:
        - assignments.submit
        - assessments.submit
    ADMINISTRATOR:
      displayName: Administrator
      description: Has access to managing the organization
      privileges:
        - "*"
      exclude:
        - assignments.submit
        - assessments.submit
        - organizations.*
    TEACHER:
      displayName: Teacher
      description: Manages students
      privileges:
        - courses.*
        - modules.*
        - moduleItems.*
        - profile.*
        - course-students.*
        - course-managers.*
        - groups.*
        - meetings.moderate
        - students.*
        - student.groups.*
        - discussion-groups.*
        - chat.*
      exclude:
        - courses.view-all
    STUDENT:
      displayName: Student
      description: This is just a student
      privileges:
        - modules.read
        - moduleItems.read
        - courses.read
        - profile.*
        - course-managers.view
        - groups.*
        - discussion-groups.view
        - discussion-groups.list
        - discussion-groups.post
        - assessments.submit
        - assignments.submit
        - meetings.subscribe
        - chat.directMessage
      exclude: []
