
# Jenkins uses jenkins-master-harbor to push docker images to harbor after building them
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjb3JlLmhhcmJvci5kb29yd2FyZC50ZWNoIjp7InVzZXJuYW1lIjoiamVua2lucyIsInBhc3N3b3JkIjoiaGZoZzQ1NkRGZ2g3OFNWR1NIRndkZ2giLCJlbWFpbCI6ImRlcGxveUBkb29yd2FyZC50ZWNoIiwiYXV0aCI6ImFtVnVhMmx1Y3pwb1ptaG5ORFUyUkVabmFEYzRVMVpIVTBoR2QyUm5hQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2020-07-12T04:50:38Z"
  name: jenkins-master-harbor
  namespace: default
type: kubernetes.io/dockerconfigjson


# Jenkins uses this secret to make changes in Digital Ocean
---
apiVersion: v1
data:
  .token: NmM5MjAyNDliYmUzMmZjOTYxMWM0MzYwMWNlN2RmNjhiMjM1ZmU5NDczZWYwNWZiNjYwNmFjN2YwODkzZmNhYwo=
kind: Secret
metadata:
  creationTimestamp: "2020-07-12T04:50:38Z"
  name: jenkins-do-admin
  namespace: default

# Jenkins uses this secret to modify and manage DNS changes in AWS zone doorward.tech
---
apiVersion: v1
data:
  .access_key: QUtJQVEzNk9CVDVXMkZPSkRJTUUK
  .secret_key: QjRhY3RoNGs2aXNtVkxYR2ZOdUZ5eW5jQ2xTR01rUzVISm9lbFplMQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: route53-zone-admin
  namespace: default

# Jenkins uses this ssh key to login to other servers
---
apiVersion: v1
data:
  .private_key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUExSTQ2alRXTHVDNkw2QkNBcHVtdkdkK3RVSnJvMk9CbFBmeFZTVGR4YXZKRWpMejB0OUtWCnF5VFhDaGZ4UGlSSnZhYzN4OVdzN0RPV3hLTU1ISU9VMTVCT2lCL1U5dC8vbXBTZVlkY1VIUXFrUnVkdlBES2ZwODZJalYKZnpmMGdzdGlFaFo3RXhKUGFna21uUFg0NjVNQk5iVk1CbDNOYWZqMFFjWXM3OWtySkdwY1Jyd2h4ejRINWp4eHQ3T01lZwo4YnN0YkJEYWVjTEltNVNDZEJhUS9hcXAyYXRvYkFYY2VVcll3V0NJZUwyaHZxOGlPVnpGQUJUUDVNTUQ3WFU0ME1PNDVlCmVQb3ZhZ25WVEdWYkdiZ2hEZW9tTXJZTmRlSU5pZXl0TnkwQVZOTlNMOHd3dklrUEZ6c3l0cmc3TzB3OUQyNUhoT1ZoM0wKOG82a0Q3MlZXd0FBQTlnYnc3bDRHOE81ZUFBQUFBZHpjMmd0Y25OaEFBQUJBUURVampxTk5ZdTRMb3ZvRUlDbTZhOFozNgoxUW11alk0R1U5L0ZWSk4zRnE4a1NNdlBTMzBwV3JKTmNLRi9FK0pFbTlwemZIMWF6c001YkVvd3djZzVUWGtFNklIOVQyCjMvK2FsSjVoMXhRZENxUkc1Mjg4TXArbnpvaU5WL04vU0N5MklTRm5zVEVrOXFDU2FjOWZqcmt3RTF0VXdHWGMxcCtQUkIKeGl6djJTc2thbHhHdkNISFBnZm1QSEczczR4NkR4dXkxc0VOcDV3c2libElKMEZwRDlxcW5acTJoc0JkeDVTdGpCWUloNAp2YUcrcnlJNVhNVUFGTS9rd3dQdGRUalF3N2psNTQraTlxQ2RWTVpWc1p1Q0VONmlZeXRnMTE0ZzJKN0swM0xRQlUwMUl2CnpEQzhpUThYT3pLMnVEczdURDBQYmtlRTVXSGN2eWpxUVB2WlZiQUFBQUF3RUFBUUFBQVFFQXBvVXlxOVFLUE9ZQ1ozRWUKU1NXRUw0SUQxc1UxckVySUpqS2NZanJVV1JPcHpwUnVKK0VMcmtPelVFNEhpa2FGbXRYNUprNXBKYmNZNDc1VXk3WHVFcAo4VVZ5S1JCa1Bnaktyb0ZnQ1kybE91OVhsMHRMVjRUTS9LUE9sdGN3Y0pPRHBtWUVUNkdsbzQyOXVYUWVhZmdHRjV5TURlClRJKzcrMUpCNXNzQTd6M2NCeEw2bFk0VGdDQmVvdHZteTc0M3c2MUd3Tjl4R2N6Wk1VbzFnYmM3VldScHBkSXB6YkpFSjgKaDFRQWQwaFp5a3hOS0UzN0dBcDhvT0xkRGRtMUphTXNlN205TjE5N20yR1UycG5lOHpRaVp6b0xkdlJSSFYyQXZrZ24vVgpJVW9oODFoYVk4VHZFWmdTbzI0aFVyRTNrbTd6UCswcWtmb05MaTBNV05ZbmdRQUFBSUJiQS94MEcxaGpseHIweTRNdVppClVDVCtuQTN5cVJFb1RWc01jdTZSMEp5MTB4U01DRFREcC82cnRtWHJLTkZFcGgwMGdLM3NkUExLbEVuVlBrcTJ5VVVQMSsKVTE1UytreW5hTmxZVXVIci93eTZZY1lNRWRpSFVMM3ZhRVgrRVBXTlNVRlJoaEpPVDgyMXhrYjRNd1FOUXRSUTQvNnBsVQpKdll4dWJpZWY4b3dBQUFJRUE2c3g4WlBqdzY0cVFOQ0orUE1wOG1KaytYVGJhdFU1SGFqR3VHcVkzZWZibFpFL0poM0RPCnBndWNmOVhzeGxPWHJsRWNFNUs3Z0xWbTVqL2pXaEdOamNHc0tENHdxTkVxeHRxd3JtRnFYWCtDSUg0UXFhcHE3SkI4bjYKSjI2TGROaXdkSHdlTmlpblhYOGt2bFNoZGlYeU9zMTNZYnNQdm11YlZPOHVZdWtVRUFBQUNCQU9lL2svNzhKUFhzYjRwLwpoU2hxQW82M1JJTnVlY0JpbDk2R2NYdXFBZ2J4ZUtwWFJRZGVxdVV2WXcvOGFwRDQzSEc4NkF2ZlluSUszNzVnSXF5YSswCkxJMXE4djQ0Y3MrN1B1VDJwY2J1em81VTFXQ3dsUHRIa050eThxcDBNNVVNRkhmUDZYYUFLMnp4eXllWjQwbXdtTXZoL08KUUhzU2lzMDEvaS8zLytPYkFBQUFJV0poYzJsc1FGVlRSVkl0Ym04dFRXRmpRbTl2YXkxUWNtOHRNaTVzYjJOaGJBRT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: jenkins-ssh-key
  namespace: default


# Jenkins use these credentials to creating new jobs using jenkins job builder plugin
---
apiVersion: v1
data:
  .ini-file: W2pvYl9idWlsZGVyXQppZ25vcmVfY2FjaGU9VHJ1ZQprZWVwX2Rlc2NyaXB0aW9ucz1GYWxzZQppbmNsdWRlX3BhdGg9LgpyZWN1cnNpdmU9RmFsc2UKYWxsb3dfZHVwbGljYXRlcz1GYWxzZQoKW2plbmtpbnNdCnVzZXI9amVua2lucy1qb2ItYnVpbGRlcgpwYXNzd29yZD0xMTFkNzUzNTVhODVjZDFlMTJkNDVlY2JiNTY2NmY1YWU4CnVybD1odHRwczovL2NpLmRvb3J3YXJkLnRlY2gK
kind: Secret
metadata:
  creationTimestamp: null
  name: jenkins-builder
  namespace: default
