organization:
  name: "doorward"
  displayName: "Doorward E-Learning"
  hosts: localhost:3000,doorward.local:3000
  lang: en
  descriptiveLogo: false
  email: info@doorward.tech
  logos:
    light: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862570/Doorward/logo/Doorward_Logo_Small.png"
    dark: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862550/Doorward/logo/Doorward_Logo_Small_Dark.png"
  description: ''
  meetingPlatform: Jitsi
