apiVersion: v1
kind: Service
metadata:
  name: {{ include "osyathdb.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-edudoor
  labels:
    {{- include "osyathdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "osyathdb.selectorLabels" . | nindent 4 }}
