export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST';
export const ADD_MEMBER = 'ADD_MEMBER';
export const GET_MEMBER = 'GET_MEMBER';
export const CHANGE_MEMBERS_PASSWORD = 'CHANGE_MEMBERS_PASSWORD';
export const CHANGE_MEMBERS_ACCOUNT_INFORMATION = 'CHANGE_MEMBERS_ACCOUNT_INFORMATION';
