releases:
  - name: show-config
    namespace: show-doorward
    labels:
      stage: 0
      name: config
    chart: ../../charts/apps/config
    values:
      - config.yaml

  - name: show-thaladb
    namespace: show-doorward
    labels:
      stage: 1
      name: thaladb
    chart: ../../charts/apps/thaladb
    values:
      - config.yaml

  - name: show-samvadam
    namespace: show-doorward
    labels:
      stage: 2
      name: samvadam
    chart: ../../charts/apps/samvadam
    needs:
      - show-doorward/show-thaladb
    values:
      - config.yaml

  - name: show-thala
    namespace: show-doorward
    labels:
      stage: 2
      name: thala
    chart: ../../charts/apps/thala
    needs:
      - show-doorward/show-thaladb
    values:
      - config.yaml

  - name: show-chuchu
    namespace: show-doorward
    labels:
      stage: 2
      name: chuchu
    chart: ../../charts/apps/chuchu
    needs:
      - show-doorward/show-thaladb
    values:
      - config.yaml

  - name: show-vidu
    namespace: show-doorward
    labels:
      stage: 2
      name: vidu
    chart: ../../charts/apps/vidu
    needs:
      - show-doorward/show-thaladb
    values:
      - config.yaml
