apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thaladb.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-edudoor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
