export const routeNames = () => {
  return {
    addAssignment: t.addAssignment,
    addCourseStudent: t.addCourseStudent,
    addModulePage: 'Add Page',
    addQuiz: 'Create Quiz',
    addExam: 'Create Exam',
    exam: 'Exam',
    quiz: 'Quiz',
    addStudentGroup: 'Add Student Group',
    addTeacher: 'Add Teacher',
    addTeacherGroup: 'Add Teacher Group',
    assignmentList: 'Assignments',
    changePassword: 'Change Password',
    chat: 'Chat',
    classrooms: 'Classrooms',
    courseList: 'All Courses',
    courseListReports: 'Courses Reports',
    courseStudents: 'Students taking course',
    courses: 'Courses',
    createCourse: 'Create Course',
    createOrganization: 'Create Organization',
    createPassword: 'Create Password',
    dashboard: 'Dashboard',
    editModuleItem: 'Edit Module Item',
    editOrganization: 'Edit Organization',
    editStudentGroup: 'Edit Student Group',
    forgotPassword: 'Forgot password',
    groups: 'Groups',
    home: 'Home',
    login: 'Login',
    moduleItems: 'Module Items',
    modules: 'Modules',
    myProfile: 'My Profile',
    newStudent: 'Add Student',
    organizations: 'Organizations',
    password: 'Password',
    register: 'Register',
    reports: 'Reports',
    resetPassword: 'Reset password',
    schoolClassrooms: 'Classrooms',
    studentGroups: 'Student Groups',
    studentList: 'All Students',
    studentListReports: 'Student Reports',
    studentReport: 'Student Report',
    students: t.students,
    teacherGroups: 'Teacher Groups',
    teacherList: 'All Teachers',
    teacherListReports: 'Teacher Reports',
    teacherReport: 'Teacher Report',
    teachers: 'Teachers',
    videoCall: 'Video Call',
    viewCourse: 'View Course',
    viewModuleItem: 'Module Item',
    viewStudent: 'View Student',
    viewStudentGroup: 'View Student Group',
    viewTeacherGroup: 'View Teacher Group',
    updateStudentGroup: 'Update',
    discussionGroups: 'Discussion Groups',
    viewDiscussionGroup: 'View Discussion Group',
  };
};
