export const routeNames = {
  addAssignment: 'Create Assignment',
  addForumMember: 'Add Member',
  addModulePage: 'Add Page',
  addQuiz: 'Create Quiz',
  addMemberGroup: 'Add Member Group',
  addModerator: 'Add Moderator',
  addModeratorGroup: 'Add Moderator Group',
  assignmentList: 'Assignments',
  changePassword: 'Change Password',
  chat: 'Chat',
  classrooms: 'Classrooms',
  forumList: 'All Meetings',
  forumListReports: 'Forums Reports',
  forumMembers: 'Members taking forum',
  forums: 'Meetings',
  createForum: 'Create Meeting',
  createOrganization: 'Create Organization',
  createPassword: 'Create Password',
  dashboard: 'Dashboard',
  editModuleItem: 'Edit Module Item',
  editOrganization: 'Edit Organization',
  editMemberGroup: 'Edit Member Group',
  forgotPassword: 'Forgot password',
  groups: 'Groups',
  home: 'Home',
  login: 'Login',
  moduleItems: 'Module Items',
  modules: 'Modules',
  myProfile: 'My Profile',
  newMember: 'Add Member',
  organizations: 'Organizations',
  password: 'Password',
  register: 'Register',
  reports: 'Reports',
  resetPassword: 'Reset password',
  schoolClassrooms: 'Classrooms',
  memberGroups: 'Member Groups',
  memberList: 'All Members',
  memberListReports: 'Member Reports',
  memberReport: 'Member Report',
  members: 'Members',
  moderatorGroups: 'Moderators Groups',
  moderatorList: 'All Moderators',
  moderatorListReports: 'Moderator Reports',
  moderatorReport: 'Moderator Report',
  moderators: 'Moderators',
  videoCall: 'Video Call',
  viewForum: 'View Forum',
  viewModuleItem: 'Module Item',
  viewMember: 'View Member',
  viewMemberGroup: 'View Member Group',
  viewModeratorGroup: 'View Moderator Group',
  updateMemberGroup: 'Update',
};
