apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meeting.fullname" . }}
  namespace: myaccount-doorward
  labels:
    {{- include "meeting.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "meeting.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "meeting.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "meeting.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.meeting.repository }}:{{ .Values.image.meeting.version }}"
          imagePullPolicy: {{ .Values.image.meeting.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 100
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: {{ .Values.service.targetport }}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: {{ .Values.container.startupseconds }}
            successThreshold: 1
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .Values.service.targetport }}
          env:
            - name: OPENVIDU_API_PORT
              valueFrom:
                configMapKeyRef:
                  key: OPENVIDU_API_PORT
                  name: myaccount-config
            - name: OPENVIDU_API_URL
              valueFrom:
                configMapKeyRef:
                  key: OPENVIDU_API_URL
                  name: myaccount-config
            - name: REACT_APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_APP_BASE_URL
                  name: myaccount-config
            - name: REACT_APP_OPENVIDU_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_APP_OPENVIDU_URL
                  name: myaccount-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
