# Name of the Customer / Website
customer: prod
# Customer type (Options are school-india, school-international, college-india, college-international, institute-india, institute-international, corporate-india, corporate-international)
customer-type: college-india
# HOME Page of the website. Default Value: https://<customer-name>.doorward.tech.
app_domain: prod.doorward.org
# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
welcomepage_domain: beta.doorward.org
# Application URL. Default Value: https://<customer-name>.doorward.tech
app_url: https://prod.doorward.org
# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.tech
samvadam_domain: samvadam.prod.doorward.tech
# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.tech
thala_domain: thala.prod.doorward.org
# Public Domain of meet ui
meet_domain: meet.prod.doorward.org
# Public Chat Domain
chat_domain: chat.prod.doorward.org
# Public Domain for jitsi host
meet_host: alpha.jitsi.net
# Public Domain for openvidu API.
openviduapi_url: https://vidu.prod.doorward.tech/api/
# Public Domain for OpenVidu API
openviduapi_domain: vidu.prod.doorward.tech
# Public URL of Openvidu Server
classrooms_url: classrooms.edudoor.org
# Name of the Website. Default Value: <Customer-Name>
websitename: prod
# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: prod-doorward
chatdbpassword: Fhs63jPdfe3
postgres_password: Fhs63jPdfe3
# Secret to use to pull docker images for deployment
imagePullSecrets:
  - name: deploy-pull-mumbai
# Resources
resources:
  requests:
    cpu: 150m
    memory: 256Mi
# How many replicas
replicaCount: 2
# Override default variables for stage environments
timezone: "Asia/Kolkata"
image:
  swagat:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward-elearning/swagat@sha256
    version: e82518b985dd8733e45d1923885aa7be3807a759a6622d8166103242fba21e8b
    pullPolicy: Always
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward-elearning/thala@sha256
    version: 9cb9ec3780c429613718c3812fcefa17b23ac9a92ba39e0a45982ba671976377
    pullPolicy: Always
  samvadam:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward-elearning/chuchu@sha256
    version: f9fbe32c92a15dafd67338160b900ea2119ed92f84365cd817d32dc5266f3a58
    pullPolicy: Always
  vidu:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/vidu
    version: 1.1.2-beta
    pullPolicy: Always
  meet:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/meet
    version: 1.0.0
    pullPolicy: Always
  chat:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward-elearning/chat@sha256
    version: 236303918143a112fec3108f5a7a2753856768dd408e879428e6d271e8e14b93
    pullPolicy: Always
organization:
  # Organization Logo
  logo: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862570/Doorward/logo/Doorward_Logo_Small.png"
  # Display Name of Organization
  name: "Doorward E-Learning"
  # Application URL
  website: prod.doorward.tech
  #Organization Admin Email ID
  email: info@doorward.tech
# Organization Settings
DEFAULT_ORGANIZATION_NAME: prod
DEFAULT_ORGANIZATION_DISPLAY_NAME: "Doorward E-Learning"
ORGANIZATION_INGRESS_URL: "https://argoevents.doorward.tech/organization-ingress"
organization:
  name: "doorward"
  displayName: "Doorward E-Learning"
  hosts: prod.doorward.org
  lang: en
  descriptiveLogo: false
  email: info@doorward.tech
  logos:
    light: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862570/Doorward/logo/Doorward_Logo_Small.png"
    dark: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862550/Doorward/logo/Doorward_Logo_Small_Dark.png"
  description: ''
  meetingPlatform: Jitsi
  users:
    - firstName: system
      lastName: admin
      email: gitaumoses4@gmail.com
      username: superadmin
      password: password
      zipCode: ''
      country: India
      city: Anantapur
      status: Active
      role: SUPER_ADMINISTRATOR
      rootOrganizationOnly: true
    - firstName: system
      lastName: admin
      email: gitaumoses4@gmail.com
      username: administrator
      password: password
      zipCode: ''
      country: India
      city: Anantapur
      status: Active
      role: ADMINISTRATOR
  roles:
    SUPER_ADMINISTRATOR:
      displayName: Super Administrator
      description: Has full access to the system
      rootOrganizationOnly: true
      privileges:
        - "*"
      exclude:
        - assignments.submit
        - assessments.submit
    ADMINISTRATOR:
      displayName: Administrator
      description: Has access to managing the organization
      privileges:
        - "*"
      exclude:
        - assignments.submit
        - assessments.submit
        - organizations.*
    TEACHER:
      displayName: Teacher
      description: Manages students
      privileges:
        - courses.*
        - modules.*
        - moduleItems.*
        - profile.*
        - course-students.*
        - course-managers.*
        - groups.*
        - meetings.moderate
        - students.*
        - student.groups.*
        - discussion-groups.*
        - chat.*
      exclude:
        - courses.view-all
    STUDENT:
      displayName: Student
      description: This is just a student
      privileges:
        - modules.read
        - moduleItems.read
        - courses.read
        - profile.*
        - course-managers.view
        - groups.*
        - discussion-groups.view
        - discussion-groups.list
        - discussion-groups.post
        - assessments.submit
        - assignments.submit
        - meetings.subscribe
        - chat.directMessage
      exclude: []
