apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thaladb.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-doorward
  labels:
    {{- include "thaladb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "thaladb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thaladb.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.thaladb.repository }}:{{ .Values.image.thaladb.version }}"
          imagePullPolicy: {{ .Values.image.thaladb.pullPolicy }}
          ports:
            - name: {{ .Values.service.protocol }}
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: {{ .Values.service.targetport }}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: {{ .Values.container.startupseconds }}
            successThreshold: 1
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .Values.service.targetport }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: {{ .Values.customer -}}-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: {{ .Values.customer -}}-config
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: {{ .Values.customer -}}-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ include "thaladb.fullname" . }}
              subPath: postgres
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ include "thaladb.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ include "thaladb.fullname" . }}
      - emptyDir: {}
        name: postgresdb

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
