# Name of the Customer / Website
customer: stage
# Customer type (Options are school-india, school-international, college-india, college-international, institute-india, institute-international, corporate-india, corporate-international)
customer-type: college-india
# HOME Page of the website. Default Value: https://<customer-name>.doorward.tech.
app_domain: stage.doorward.org
# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
welcomepage_domain: beta.doorward.org
# Application URL. Default Value: https://<customer-name>.doorward.tech
app_url: https://stage.doorward.org
# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.tech
samvadam_domain: samvadam.stage.doorward.tech
# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.tech
thala_domain: thala.stage.doorward.org
# Public Domain of meet ui
meet_domain: meet.stage.doorward.org
# Public Chat Domain
chat_domain: chat.stage.doorward.org
# Public Domain for jitsi host
meet_host: alpha.jitsi.net
# Public Domain for openvidu API.
openviduapi_url: https://vidu.stage.doorward.tech/api/
# Public Domain for OpenVidu API
openviduapi_domain: vidu.stage.doorward.tech
# Public URL of Openvidu Server
classrooms_url: classrooms.edudoor.org
# Name of the Website. Default Value: <Customer-Name>
websitename: stage
# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: stage-doorward
chatdbpassword: 6Epnyablastag
postgres_password: 6Epnyablastag
# Secret to use to pull docker images for deployment
imagePullSecrets:
  - name: deploy-pull-mumbai
# Override default variables for stage environments
timezone: "Asia/Kolkata"
image:
  swagat:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/swagat@sha256
    version: 6818d42ea1ccecdfaeb6e213f127fa26027711a24d3cd590d5f94457d0388596
    pullPolicy: Always
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/thala@sha256
    version: ab7ff7a3ddffe863e8dd4ab00598ea882fd2de713d78ebb33e1bdcd0db62a3a6
    pullPolicy: Always
  samvadam:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/chuchu@sha256
    version: f474ffe94058cc2921da165406aca719b48531a9ea8e8e8fc5f725858f65a05b
    pullPolicy: Always
  vidu:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/vidu
    version: 1.1.2-beta
    pullPolicy: Always
  meet:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/meet
    version: 1.0.0
    pullPolicy: Always
  chat:
    repository: 210607809234.dkr.ecr.ap-south-1.amazonaws.com/doorward/chat@sha256
    version: 3fb044f810e5dd78060375b4be45d805242e66ed574b34abed218df550d22163
    pullPolicy: Always
organization:
  # Organization Logo
  logo: "https://res.cloudinary.com/dldhztrbs/image/upload/v1605862570/Doorward/logo/Doorward_Logo_Small.png"
  # Display Name of Organization
  name: "Doorward E-Learning"
  # Application URL
  website: stage.doorward.tech
  #Organization Admin Email ID
  email: info@doorward.tech
