export const CREATE_COURSE = 'CREATE_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';
export const VIEW_COURSE = 'VIEW_COURSE';
export const CREATE_COURSE_MODULE = 'CREATE_COURSE_MODULE';
export const FETCH_COURSE_STUDENTS = 'FETCH_COURSE_STUDENTS';
export const CREATE_COURSE_STUDENT = 'CREATE_COURSE_STUDENT';
export const FETCH_STUDENTS_NOT_REGISTERED = 'FETCH_STUDENTS_NOT_REGISTERED';
export const ADD_MODULE_ITEM = 'ADD_MODULE_ITEM';
