# Name of the Customer / Website
customer: drashoksacademy

# HOME Page of the website. Default Value: https://<customer-name>.doorward.org.
app_domain: drashoksacademy.doorward.org

# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
welcomepage_domain: www.doorward.org

# Application URL. Default Value: https://<customer-name>.doorward.org
app_url: https://drashoksacademy.doorward.org

# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.org
samvadam_domain: samvadam.drashoksacademy.doorward.org

# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.org
thala_domain: thala.drashoksacademy.doorward.org

# Name of the Website. Default Value: <Customer-Name>
websitename: drashoksacademy

# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: drashoksacademy-doorward

# Override default variables for stage environments

image:
  swagat:
    repository: gcr.io/doorwardlms/swagat
    version: 1.1.0
    pullPolicy: IfNotPresent
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: gcr.io/doorwardlms/thala
    version: 1.1.0
    pullPolicy: IfNotPresent
  samvadam:
    repository: gcr.io/doorwardlms/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: gcr.io/doorwardlms/chuchu
    version: 1.1.0
    pullPolicy: IfNotPresent

organization:
  # Organization Logo
  logo: "https://doorwardlms.s3.amazonaws.com/drashoksacademy.png"
  # Display Name of Organization
  name: Dr Ashok's Academy
  # Application URL
  website: drashoksacademy.doorward.org
  #Organization Admin Email ID
  email: drashokgopalakrishnan@gmail.com
