apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: databases
  namespace: basil-edudoor

provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate

