apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2019-12-14T06:17:57Z"
  generation: 3
  labels:
    app: edudoor-database
  name: edudoor-database
  namespace: basil-edudoor
  resourceVersion: "5168008"
  selfLink: /apis/apps/v1/namespaces/basil-edudoor/deployments/edudoor-database
  uid: 78e26681-1e39-11ea-812a-42010a8e0185
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: edudoor-database
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: edudoor-database
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: edudoor-database-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: edudoor-database-config
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: edudoor-database-config
        image: postgres:9.6-alpine
        imagePullPolicy: IfNotPresent
        name: postgres
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: edudoor-data-postgresql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: edudoor-data-postgresql
        persistentVolumeClaim:
          claimName: edudoor-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-02T06:25:16Z"
    lastUpdateTime: "2020-01-02T06:25:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-14T06:17:57Z"
    lastUpdateTime: "2020-01-02T09:40:43Z"
    message: ReplicaSet "edudoor-database-66cd5f4956" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
