apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-12-14T06:23:11Z"
  generation: 2
  labels:
    app: openolat-database
  name: openolat-database
  namespace: basil-doorward
  resourceVersion: "5130290"
  selfLink: /apis/apps/v1/namespaces/basil-doorward/deployments/openolat-database
  uid: 33d2c03f-1e3a-11ea-812a-42010a8e0185
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openolat-database
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openolat-database
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: openolat-database-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: openolat-database-config
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: openolat-database-config
        image: gcr.io/doorward/doorward_database@sha256:a7be6cc9f47915913a22cbf9fe7c95881bb566a4d21c0d5e2b6d556c1c7d3d02
        imagePullPolicy: IfNotPresent
        name: doorward-database-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: openolat-data-postgresql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: openolat-data-postgresql
        persistentVolumeClaim:
          claimName: openolat-data

status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-14T06:23:11Z"
    lastUpdateTime: "2019-12-14T06:23:15Z"
    message: ReplicaSet "openolat-database-ddb9bc7c9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-02T06:25:19Z"
    lastUpdateTime: "2020-01-02T06:25:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
