version: '2.1'

volumes:
  openolat_data:
    external: true
  edudoor_data:
    external: true

services:
  edudoor_frontend:
    image: gitaumoses4/edudoor_frontend
    container_name: edudoor_frontend
    links:
      - edudoor_rest_api
    environment:
      REACT_APP_BASE_URL: http://lms.makonis.ai/api/v1/
      REACT_APP_REQUEST_DELAY: 500
    ports:
      - '3005:8000'
    expose:
      - '8000'
    depends_on:
      edudoor_rest_api:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:8000']
      interval: 10s
      timeout: 10s
      retries: 20
  edudoor_rest_api:
    image: gitaumoses4/edudoor_backend
    container_name: edudoor_node_backend
    links:
      - edudoor_node_database
    environment:
      DATABASE_URL: postgres://postgres:postgres@edudoor_node_database/edudoor
      OPENOLAT_API_URL: http://edudoor_openolat_backend:8080/openolat/restapi
    ports:
      - '7000:7000'
    expose:
      - '7000'
    depends_on:
      edudoor_node_database:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:7000']
      interval: 10s
      timeout: 10s
      retries: 20
  openolat:
    image: gitaumoses4/openolat-edudoor
    container_name: edudoor_openolat_backend
    links:
      - openolat_database
    ports:
      - '5000:8080'
    depends_on:
      openolat_database:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:8080']
      interval: 10s
      timeout: 10s
      retries: 20
  openolat_database:
    image: gitaumoses4/edudoor_database
    container_name: openolat_database
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openolat
    volumes:
      - openolat_data:/var/lib/postgresql/openolat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
  edudoor_node_database:
    image: postgres:9.6-alpine
    container_name: edudoor_node_backend_db
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edudoor
    depends_on:
      openolat:
        condition: service_started
    volumes:
      - edudoor_data:/var/lib/postgresql/edudoor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
