version: '2.1'

volumes:
  openolat_data:
    external: true
  doorward_data:
    external: true

services:
  doorward_frontend:
    image: gitaumoses4/doorward_frontend
    container_name: doorward_frontend
    links:
      - doorward_rest_api
    environment:
      REACT_APP_BASE_URL: http://lms.makonis.ai/api/v1/
      REACT_APP_REQUEST_DELAY: 500
    ports:
      - '3005:5000'
    expose:
      - '5000'
    depends_on:
      doorward_rest_api:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:8000']
      interval: 10s
      timeout: 10s
      retries: 20
  doorward_rest_api:
    image: gitaumoses4/doorward_backend
    container_name: doorward_node_backend
    links:
      - doorward_node_database
    environment:
      DATABASE_URL: postgres://postgres:postgres@doorward_node_database/doorward
      OPENOLAT_API_URL: http://doorward_openolat_backend:8080/openolat/restapi
    ports:
      - '7000:7000'
    expose:
      - '7000'
    depends_on:
      doorward_node_database:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:7000']
      interval: 10s
      timeout: 10s
      retries: 20
  openolat:
    image: gitaumoses4/openolat-doorward
    container_name: doorward_openolat_backend
    links:
      - openolat_database
    ports:
      - '5000:8080'
    depends_on:
      openolat_database:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s localhost:8080']
      interval: 10s
      timeout: 10s
      retries: 20
  openolat_database:
    image: gitaumoses4/doorward_database
    container_name: openolat_database
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openolat
    volumes:
      - openolat_data:/var/lib/postgresql/openolat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
  doorward_node_database:
    image: postgres:9.6-alpine
    container_name: doorward_node_backend_db
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doorward
    depends_on:
      openolat:
        condition: service_started
    volumes:
      - doorward_data:/var/lib/postgresql/doorward
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
