CUSTOMER_NAME: show
APP_VERSION: 1.1.1

LOGO_URL: "https://doorward.s3.amazonaws.com/logos/download1.png"

ORGANIZATION_DISPLAY_NAME: "Show"

APP_WEBSITE_NAME: "show1.doorward.tech"

ORGANIZATION_ADMIN_EMAIL: "info@doorward.tech"

WELCOME_WEBSITE_NAME: "www.doorward.tech"

TEACHER_UPLOAD_SPEED_MAX: 31

TEACHER_UPLOAD_SPEED_MIN: 21

STUDENT_DOWNLOAD_SPEED_MAX: 31

STUDENT_DOWNLOAD_SPEED_MIN: 21

WEEK_START_DAY: sunday

WEEK_END_DAY: sunday

CLASS_START_TIME: 4

CLASS_END_TIME: 4
