export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const UPDATE_ACCOUNT_INFORMATION = 'UPDATE_ACCOUNT_INFORMATION';
export const UPDATE_ACCOUNT_PASSWORD = 'UPDATE_ACCOUNT_PASSWORD';
export const CREATE_ACCOUNT_PASSWORD = 'CREATE_ACCOUNT_PASSWORD';
