apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
  name: {{ include "staticingress.fullname" . }}
  labels:
    {{- include "staticingress.labels" . | nindent 4 }}

spec:
  rules:
    - host: api.clients.edudoor.org
      http:
        paths:
          - backend:
              serviceName: corteza-server
              servicePort: 80
            path: /

    - host: clients.edudoor.org
      http:
        paths:
          - backend:
              serviceName: corteza-webapp
              servicePort: 80
            path: /

    - host: ci.edudoor.org
      http:
        paths:
          - backend:
              serviceName: edudoor-ciserver-jenkins
              servicePort: 80
            path: /

  tls:
  - hosts:
    - api.clients.edudoor.org
    - clients.edudoor.org
    - ci.edudoor.org
    secretName: clients.edudoor.org
