apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
  name: {{ include "staticingress.fullname" . }}
  labels:
    {{- include "staticingress.labels" . | nindent 4 }}

spec:
  rules:
    - host: api.clients.doorward.org
      http:
        paths:
          - backend:
              serviceName: corteza-server
              servicePort: 80
            path: /

    - host: clients.doorward.org
      http:
        paths:
          - backend:
              serviceName: corteza-webapp
              servicePort: 80
            path: /

    - host: ci.doorward.org
      http:
        paths:
          - backend:
              serviceName: doorward-ciserver-jenkins
              servicePort: 80
            path: /

    - host: docs.doorward.org
      http:
        paths:
          - backend:
              serviceName: books-bookstack
              servicePort: 80
            path: /

    - host: www.doorward.org
      http:
        paths:
          - backend:
              serviceName: books-bookstack
              servicePort: 80
            path: /docs

    - host: doorward.org
      http:
        paths:
          - backend:
              serviceName: books-bookstack
              servicePort: 80
            path: /docs

  tls:
  - hosts:
    - api.clients.doorward.org
    - clients.doorward.org
    - ci.doorward.org
    - docs.doorward.org
    secretName: clients.doorward.org
