apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.registry" . }}"
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-hostname: core.harbor.doorward.tech
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - name: registry
      port: {{ template "harbor.registry.servicePort" . }}
    - name: controller
      port: {{ template "harbor.registryctl.servicePort" . }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry
