pipeline {
  agent any

  parameters {
      string(name: 'APP_VERSION', defaultValue: '1.2.1', description: 'Version of the application to be deployed?')
  }

  stages {
    stage('Deploy') {
        steps {
          dir('helm/environments/tesolpro'){
            sh 'helmfile -l stage=0 sync'
          }
          sh 'sleep 10'
          dir('helm/environments/tesolpro'){
            sh 'helmfile -l stage=0 sync'
            sh 'helmfile -l stage=1 sync'
            sh 'sleep 100'
            sh 'helmfile -l stage=2 sync'
            sh 'helmfile -l stage=3 sync --set image.chuchu.version=${APP_VERSION} --set image.thala.version=${APP_VERSION} '
            sh 'helmfile -l stage=4 sync'
          }
        }
    }
  }
  post {
       success {
           mail bcc: '', body: 'tesolpro.doorward.tech is successfully deployed. Please wait for 5 minutes for the website to become Online.', cc: '', charset: 'UTF-8', from: 'jenkins@doorward.tech', mimeType: 'text/html', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "basil@doorward.tech,moses@doorward.tech,madhu@doorward.tech,sreenath@doorward.tech";
       }
       failure {
           mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'jenkins@doorward.tech', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "basil@doorward.tech,moses@doorward.tech,madhu@doorward.tech,sreenath@doorward.tech";
       }
  }

}
