export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const UPDATE_MY_ACCOUNT_INFORMATION = 'UPDATE_MY_ACCOUNT_INFORMATION';
export const UPDATE_MY_ACCOUNT_PASSWORD = 'UPDATE_MY_ACCOUNT_PASSWORD';
export const CREATE_ACCOUNT_PASSWORD = 'CREATE_ACCOUNT_PASSWORD';
export const FORGOT_ACCOUNT_PASSWORD = 'FORGOT_ACCOUNT_PASSWORD';
