- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Generate newcustomer-vars.yaml
      template:
        src: newcustomer-vars.yaml.j2
        dest: "../../environments/{{ CUSTOMER_NAME }}/variables.yaml"
    - name: Include all customer environment variables
      include_vars: "../../environments/{{ CUSTOMER_NAME }}/variables.yaml"
    - name: generate config.yaml
      template:
        src: config.yaml.j2
        dest: "../../environments/{{ CUSTOMER_NAME }}/config.yaml"
    - name: helmfile
      template:
        src: helmfile.j2
        dest: "../../environments/{{ CUSTOMER_NAME }}/helmfile.yaml"
    - name: Jenkinsfile
      template:
        src: Jenkinsfile.j2
        dest: "../../environments/{{ CUSTOMER_NAME }}/Jenkinsfile"
    - name: new-jenkins-job.yaml
      template:
        src: new-jenkins-job.yaml.j2
        dest: "/tmp/new-jenkins-job.yaml"
