export const ORGANIZATION_CONNECTION = 'ORGANIZATION_CONNECTION';
export const MAIN_CONNECTION_OPTIONS = 'MAIN_CONNECTION_OPTIONS';
export const ORGANIZATIONS_CONNECTION_OPTIONS = 'ORGANIZATIONS_CONNECTION_OPTIONS';
