export enum MeetingCapabilities {
  JOIN_WITH_ACTIVE_AUDIO = 'JOIN_WITH_ACTIVE_AUDIO',
  JOIN_WITH_ACTIVE_VIDEO = 'JOIN_WITH_ACTIVE_VIDEO',
  PUBLISH_VIDEO = 'PUBLISH_VIDEO',
  PUBLISH_AUDIO = 'PUBLISH_AUDIO',
  CHAT = 'CHAT',
  SHARE_SCREEN = 'SHARE_SCREEN',
  GO_FULL_SCREEN = 'GO_FULL_SCREEN',
  SPEAKING_LAYOUT = 'SPEAKING_LAYOUT',
  AUTO_JOIN_SESSION = 'AUTO_JOIN_SESSION',
  EXIT_MEETING = 'EXIT_MEETING',
  TURN_ON_PARTICIPANTS_VIDEO = 'TURN_ON_PARTICIPANTS_VIDEO',
  TURN_OFF_PARTICIPANTS_VIDEO = 'TURN_OFF_PARTICIPANTS_VIDEO',
  MUTE_PARTICIPANTS = 'MUTE_PARTICIPANTS',
  UNMUTE_PARTICIPANTS = 'UNMUTE_PARTICIPANTS',
  USE_WHITEBOARD = 'USE_WHITEBOARD',
}

export const defaultMeetingCapabilities = [
  MeetingCapabilities.PUBLISH_VIDEO,
  MeetingCapabilities.PUBLISH_AUDIO,
  MeetingCapabilities.CHAT,
  MeetingCapabilities.SPEAKING_LAYOUT,
  MeetingCapabilities.SHARE_SCREEN,
  MeetingCapabilities.GO_FULL_SCREEN,
  MeetingCapabilities.AUTO_JOIN_SESSION,
  MeetingCapabilities.EXIT_MEETING,
];
