# Use this docker file to develop Jenkins slave image where builds will run

FROM jenkinsci/jnlp-slave:3.40-1

USER root

RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y build-essential nodejs gcc make cmake
RUN npm install -g @nrwl/nx

