pipeline {
  agent {
    docker {
      image 'node:dubnium'
    }
  }

  environment {
    PROJECT_NAME = 'edudoor'
  }

  stages {
    stage('Load deployment environment variable file') {
      steps {
        sh "Loading variables"
      }
    }

    stage('Make all the scripts used in this build executable') {
      steps {
        sh "chmod +x jenkins/scripts/*"
      }
    }

    stage('Install dependencies') {
      steps {
        sh "yarn install"
      }
    }

    stage("Build") {
      steps {
        sh "yarn build"
      }
    }

    stage('Deploy') {
      steps {
        sh "./jenkins/scripts/build_deploy.sh"
      }
    }
  }
}
