pipeline {

  agent any
  environment {
    PROJECT_NAME = 'doorward'
  }

  stages {
    stage('Load deployment environment variable file') {
      steps {
        echo "Loading variables"
      }
    }

    stage('Make all the scripts used in this build executable') {
      steps {
        sh "chmod +x jenkins/scripts/*"
      }
    }

    stage('Install dependencies') {
      steps {
        sh "yarn install"
      }
    }

    stage("Build") {
      steps {
        sh "yarn build"
      }
    }

    stage('Deploy') {
      steps {
        sh "./jenkins/scripts/build_deploy.sh"
      }
    }
  }
}
