pipeline {

  agent {
    docker {
      image 'gcr.io/edudoor/node-jnlp-slave@sha256:b0b05b1c67a671d128a96800efe4ad92158c2a437fdee90962fa226d22c7b2de'
    }
  }

  environment {
    PROJECT_NAME = 'edudoor'
  }

  stages {
    stage('Load deployment environment variable file') {
      steps {
        sh "Loading variables"
      }
    }

    stage('Make all the scripts used in this build executable') {
      steps {
        sh "chmod +x jenkins/scripts/*"
      }
    }

    stage('Install dependencies') {
      steps {
        sh "yarn install"
      }
    }

    stage("Build") {
      steps {
        sh "yarn build"
      }
    }

    stage('Deploy') {
      steps {
        sh "./jenkins/scripts/build_deploy.sh"
      }
    }
  }
}
