export const routeNames = {
  addAssignment: 'Create Assignment',
  addCourseStudent: 'Add Student',
  addModulePage: 'Add Page',
  addQuiz: 'Create Quiz',
  addStudentGroup: 'Add Student Group',
  addTeacher: 'Add Teacher',
  addTeacherGroup: 'Add Teacher Group',
  assignmentList: 'Assignments',
  changePassword: 'Change Password',
  chat: 'Chat',
  classrooms: 'Classrooms',
  courseList: 'All Courses',
  courseListReports: 'Courses Reports',
  courseStudents: 'Students taking course',
  courses: 'Courses',
  createCourse: 'Create Course',
  createOrganization: 'Create Organization',
  createPassword: 'Create Password',
  dashboard: 'Dashboard',
  editModuleItem: 'Edit Module Item',
  editOrganization: 'Edit Organization',
  editStudentGroup: 'Edit Student Group',
  forgotPassword: 'Forgot password',
  groups: 'Groups',
  home: 'Home',
  login: 'Login',
  moduleItems: 'Module Items',
  modules: 'Modules',
  myProfile: 'My Profile',
  newStudent: 'Add Student',
  organizations: 'Organizations',
  password: 'Password',
  register: 'Register',
  reports: 'Reports',
  resetPassword: 'Reset password',
  schoolClassrooms: 'Classrooms',
  studentGroups: 'Students',
  studentList: 'All Students',
  studentListReports: 'Student Reports',
  studentReport: 'Student Report',
  students: 'Students',
  teacherGroups: 'Teachers',
  teacherList: 'All Teachers',
  teacherListReports: 'Teacher Reports',
  teacherReport: 'Teacher Report',
  teachers: 'Teachers',
  videoCall: 'Video Call',
  viewCourse: 'View Course',
  viewModuleItem: 'Module Item',
  viewStudent: 'View Student',
  viewStudentGroup: 'View Student Group',
  viewTeacherGroup: 'View Teacher Group',
};
