# Source: ghost/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "thaladb.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-edudoor
  labels:
    {{- include "thaladb.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
#  volumeName: {{ include "thaladb.fullname" . }}
  resources:
    requests:
      storage: "10Gi"


# Source: ghost/templates/pvc.yaml
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: ghost
#  labels:
#    app: "ghost"
#    chart: "ghost-9.0.4"
#    release: "ghost"
#    heritage: "Helm"
#spec:
#  accessModes:
#    - "ReadWriteOnce"
#  resources:
#    requests:
#      storage: "8Gi"
