---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "thaladb.fullname" . }}
  labels:
    {{- include "thaladb.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.databasevolume.size }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{  .Values.customer -}}-thaladb
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thaladb.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-edudoor
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: {{ .Values.databasevolume.storageClassName }}
  volumeName: {{ include "thaladb.fullname" . }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.databasevolume.size }}
