# Name of the Customer / Website
customer: makonis

customer_type: institute

# HOME Page of the website. Default Value: https://<customer-name>.doorward.org.
app_domain: lms.makonis.ai

# Welcome Page Website. Customer should provide this value if they want us to design a custom website for them
welcomepage_domain: www.doorward.org

# Application URL. Default Value: https://<customer-name>.doorward.org
app_url: https://lms.makonis.ai

# Public URL of OpenVidu: Default Value: samvadam:<customer-name>.doorward.org
samvadam_domain: samvadam.makonis.doorward.org

# Public Domain of REST API: Default Value: thala:<customer-name>.doorward.org
thala_domain: thala.makonis.doorward.org

# Name of the Website. Default Value: <Customer-Name>
websitename: Makonis

# Namespace of Kubernetes. Namespace MUST be created in Kubernetes. Default Value: <Customer-name>-doorward
namespace: makonis-doorward

# Override default variables for stage environments

image:
  swagat:
    repository: gcr.io/doorwardlms/swagat
    version: 1.1.0
    pullPolicy: IfNotPresent
  thaladb:
    repository: postgres
    version: 9.6-alpine
    pullPolicy: IfNotPresent
  thala:
    repository: core.harbor.doorward.tech/doorward/thala@sha256
    version: 780a2bcbf5750ddfb058a1ebf403b6a60ab6af5fc70094d60efa17ca65e20bc8
    pullPolicy: Always
  samvadam:
    repository: gcr.io/doorwardlms/samvadam
    version: 1.0.0
    pullPolicy: IfNotPresent
  chuchu:
    repository: core.harbor.doorward.tech/doorward/chuchu@sha256
    version: bfd6ca9298b16f59a73a664d99bf4f1b4c34da011d20fc4c1b9ad6ea377a54f6
    pullPolicy: Always

organization:
  # Organization Logo
  logo: "https://doorwardlms.s3.amazonaws.com/makonis/makonis.png"
  # Display Name of Organization
  name: Makonis
  # Application URL
  website: lms.makonis.ai
  #Organization Admin Email ID
  email: info@doorward.org
