releases:
  - name: makonis-config
    namespace: makonis-edudoor
    labels:
      stage: 0
      name: config
    chart: ../../charts/apps/config
    needs:
      - makonis-edudoor/makonis-thaladb
    values:
      - config.yaml

  - name: makonis-thaladb
    namespace: makonis-edudoor
    labels:
      stage: 1
      name: thaladb
    chart: ../../charts/apps/thaladb
    values:
      - config.yaml

  - name: makonis-samvadam
    namespace: makonis-edudoor
    labels:
      stage: 2
      name: samvadam
    chart: ../../charts/apps/samvadam
    needs:
      - makonis-edudoor/makonis-thaladb
    values:
      - config.yaml

  - name: makonis-thala
    namespace: makonis-edudoor
    labels:
      stage: 2
      name: thala
    chart: ../../charts/apps/thala
    needs:
      - makonis-edudoor/makonis-thaladb
    values:
      - config.yaml

  - name: makonis-chuchu
    namespace: makonis-edudoor
    labels:
      stage: 2
      name: chuchu
    chart: ../../charts/apps/chuchu
    needs:
      - makonis-edudoor/makonis-thaladb
    values:
      - config.yaml

  - name: makonis-vidu
    namespace: makonis-edudoor
    labels:
      stage: 2
      name: vidu
    chart: ../../charts/apps/vidu
    needs:
      - makonis-edudoor/makonis-thaladb
    values:
      - config.yaml
