export const LIST_ELECTIONS = 'LIST_ELECTIONS';
export const CREATE_ELECTION = 'CREATE_ELECTION';
export const VIEW_ELECTION = 'VIEW_ELECTION';
export const CREATE_NOMINEE = 'CREATE_NOMINEE';
export const VOTE_ELECTION = 'VOTE_ELECTION';
