apiVersion: v1
data:
  REACT_APP_BASE_URL: https://{{ include "chuchu.thalapublicurl" . -}}/api/v1
  REACT_APP_CHAT_API_URL: https://{{ include "chuchu.chatpublicurl" . -}}/api/v1
  REACT_APP_CHAT_WEBSOCKET_URL: wss://{{ include "chuchu.chatpublicurl" . -}}/
  DOORWARD_WEBSITE_LINK: https://{{ .Values.app_domain }}
  OPENVIDU_API_PORT: "{{ .Values.openviduapi_port }}"
  OPENVIDU_API_URL: {{ .Values.openviduapi_url }}
  JITSI_MEET_DOMAIN:  {{ .Values.meet_domain }}
  JITSI_HOST: {{ .Values.meet_host }}
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-14T06:23:11Z"
  labels:
    {{- include "chuchu.labels" . | nindent 4 }}
    customer: {{ .Values.customer }}
  name: {{ include "chuchu.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-doorward
