apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meet.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-doorward
  labels:
    {{- include "meet.labels" . | nindent 4 }}
    customer: {{ .Values.customer }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "meet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "meet.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.meet.repository }}:{{ .Values.image.meet.version }}"
          imagePullPolicy: {{ .Values.image.meet.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 100
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: {{ .Values.service.targetport }}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: {{ .Values.container.startupseconds }}
            successThreshold: 1
            timeoutSeconds: 2
            tcpSocket:
              port: {{ .Values.service.targetport }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/{{- .Values.timezone}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
