export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const GET_ONE_ORGANIZATION = 'GET_ONE_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const GET_CURRENT_ORGANIZATION = 'GET_CURRENT_ORGANIZATION';
