export const FETCH_MEMBER_REPORT_LIST = 'FETCH_MEMBER_REPORT_LIST';
export const FETCH_MEMBER_REPORT = 'FETCH_MEMBER_REPORT';
export const FETCH_FORUM_CREATOR_REPORT_LIST = 'FETCH_FORUM_CREATOR_REPORT_LIST';
export const FETCH_FORUM_CREATOR_REPORT = 'FETCH_FORUM_CREATOR_REPORT';
