export const FETCH_MEMBER_REPORT_LIST = 'FETCH_MEMBER_REPORT_LIST';
export const FETCH_MEMBER_REPORT = 'FETCH_MEMBER_REPORT';
export const FETCH_COURSE_CREATOR_REPORT_LIST = 'FETCH_COURSE_CREATOR_REPORT_LIST';
export const FETCH_COURSE_CREATOR_REPORT = 'FETCH_COURSE_CREATOR_REPORT';
