releases:
  - name: {{ requiredEnv "PLATFORM_ENV" }}-thaladb
    namespace: {{ requiredEnv "PLATFORM_ENV" }}-doorward
    labels:
      stage: 1
      name: thaladb
    chart: ./charts/thaladb
    values:
      - ./charts/thaladb/values.yaml
      - ./environments/{{ requiredEnv "PLATFORM_ENV" }}/config.yaml

  - name: {{ requiredEnv "PLATFORM_ENV" }}-samvadam
    namespace: {{ requiredEnv "PLATFORM_ENV" }}-doorward
    labels:
      stage: 2
      name: samvadam
    chart: ./charts/samvadam
    needs:
      - {{ requiredEnv "PLATFORM_ENV" }}-doorward/{{ requiredEnv "PLATFORM_ENV" }}-thaladb
    values:
      - ./charts/samvadam/values.yaml
      - ./environments/{{ requiredEnv "PLATFORM_ENV" }}/config.yaml

  - name: {{ requiredEnv "PLATFORM_ENV" }}-thala
    namespace: {{ requiredEnv "PLATFORM_ENV" }}-doorward
    labels:
      stage: 2
      name: thala
    chart: ./charts/thala
    needs:
      - {{ requiredEnv "PLATFORM_ENV" }}-doorward/{{ requiredEnv "PLATFORM_ENV" }}-thaladb
    values:
      - ./charts/thala/values.yaml
      - ./environments/{{ requiredEnv "PLATFORM_ENV" }}/config.yaml

  - name: {{ requiredEnv "PLATFORM_ENV" }}-chuchu
    namespace: {{ requiredEnv "PLATFORM_ENV" }}-doorward
    labels:
      stage: 2
      name: chuchu
    chart: ./charts/chuchu
    needs:
      - {{ requiredEnv "PLATFORM_ENV" }}-doorward/{{ requiredEnv "PLATFORM_ENV" }}-thaladb
    values:
      - ./charts/chuchu/values.yaml
      - ./environments/{{ requiredEnv "PLATFORM_ENV" }}/config.yaml
