releases:
  - name: myaccount-config
    namespace: myaccount-doorward
    labels:
      stage: 0
      name: config
    chart: ../../charts/apps/config
    needs:
      - myaccount-doorward/myaccount-thaladb
    values:
      - config.yaml

  - name: myaccount-thaladb
    namespace: myaccount-doorward
    labels:
      stage: 1
      name: thaladb
    chart: ../../charts/apps/thaladb
    values:
      - config.yaml

  - name: myaccount-samvadam
    namespace: myaccount-doorward
    labels:
      stage: 2
      name: samvadam
    chart: ../../charts/apps/samvadam
    needs:
      - myaccount-doorward/myaccount-thaladb
    values:
      - config.yaml

  - name: myaccount-thala
    namespace: myaccount-doorward
    labels:
      stage: 2
      name: thala
    chart: ../../charts/apps/thala
    needs:
      - myaccount-doorward/myaccount-thaladb
    values:
      - config.yaml

  - name: myaccount-chuchu
    namespace: myaccount-doorward
    labels:
      stage: 2
      name: chuchu
    chart: ../../charts/apps/chuchu
    needs:
      - myaccount-doorward/myaccount-thaladb
    values:
      - config.yaml

  - name: myaccount-vidu
    namespace: myaccount-doorward
    labels:
      stage: 2
      name: vidu
    chart: ../../charts/apps/vidu
    needs:
      - myaccount-doorward/myaccount-thaladb
    values:
      - config.yaml

  - name: myaccount-swagat
    namespace: myaccount-doorward
    labels:
      stage: 3
      name: swagat
    chart: ../../charts/apps/swagat
    needs:
      - myaccount-doorward/myaccount-thaladb
    values:
      - config.yaml
