CUSTOMER_NAME: luims
APP_VERSION: 1.1.1

LOGO_URL: "https://luims.s3.amazonaws.com/luims.jpeg"

ORGANIZATION_DISPLAY_NAME: "University of Lucknow"

APP_WEBSITE_NAME: "luims.doorward.tech"

ORGANIZATION_ADMIN_EMAIL: "archanaraj10@gmail.com"

WELCOME_WEBSITE_NAME: "www.doorward.tech"

TEACHER_UPLOAD_SPEED_MAX: 25

TEACHER_UPLOAD_SPEED_MIN: 22

STUDENT_DOWNLOAD_SPEED_MAX: 25

STUDENT_DOWNLOAD_SPEED_MIN: 22

WEEK_START_DAY: sunday

WEEK_END_DAY: sunday

CLASS_START_TIME: 4

CLASS_END_TIME: 4
