apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chuchu.fullname" . }}
  namespace: {{ required "A valid foo is required!" .Values.customer -}}-edudoor
  labels:
    {{- include "chuchu.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chuchu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chuchu.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "chuchu.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
<<<<<<<< HEAD:helm/chuchu/templates/chuchu-deployment.yaml
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: {{ .Values.service.targetport }}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: {{ .Values.container.startupseconds }}
            successThreshold: 1
            timeoutSeconds: 2
            tcpSocket:
========
            - name: {{ .Values.service.protocol }}
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetport }}
          readinessProbe:
            httpGet:
              path: /
>>>>>>>> b89136d21e3ee69f3b7cd5cd7ba8a810cd44c212:helm/osyathdb/templates/osyathdb-deployment.yaml
              port: {{ .Values.service.targetport }}
          env:
            - name: REACT_APP_BASE_URL
              valueFrom:
                configMapKeyRef:
<<<<<<<< HEAD:helm/chuchu/templates/chuchu-deployment.yaml
                  key: REACT_APP_BASE_URL
                  name: {{ include "chuchu.fullname" . }}
========
                  key: POSTGRES_USER
                  name: {{ include "osyathdb.fullname" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: {{ include "osyathdb.fullname" . }}
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: {{ include "osyathdb.fullname" . }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ include "osyathdb.fullname" . }}
              subPath: postgres
>>>>>>>> b89136d21e3ee69f3b7cd5cd7ba8a810cd44c212:helm/osyathdb/templates/osyathdb-deployment.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ include "osyathdb.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ include "osyathdb.fullname" . }}
      - emptyDir: {}
        name: postgresdb
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
